version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: my_etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: my_etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    command: ["python", "pipeline.py"]
    volumes:
      - .:/app

volumes:
  pgdata: