version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow

  airflow-webserver:
    image: apache/airflow:2.8.0
    depends_on:
      - airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__SECRET_KEY: myairflowsecret123
      AIRFLOW__LOGGING__REMOTE_LOGGING: 'False'
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_HOST: postgres    
    volumes:
      - ../dags:/opt/airflow/dags
      - ../etl:/opt/airflow/etl
      - ../data:/opt/airflow/dags/data 
    ports:
      - "8080:8080"
    networks:
      - airflow
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: myairflowsecret123
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_HOST: postgres
    volumes:
      - ../dags:/opt/airflow/dags
      - ../etl:/opt/airflow/etl
      - ../data:/opt/airflow/dags/data 
    networks:
      - airflow
    command: scheduler

volumes:
  postgres-db-volume:

networks:
  airflow: